"""
pipeline/style_rewriter.py


"""

import httpx
import json
import logging

logger = logging.getLogger(__name__)

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "mistral"

TONE_PROMPTS = {
    # FIX #1 — added "btech_student" as a proper key (was missing, caused silent fallback)
    "btech_student": """Rewrite the text below so it sounds like a real BTech student wrote it for a college report or project.

Rules:
- Write naturally — like a student explaining their project, not an AI generating text
- Avoid phrases like "it is worth noting", "furthermore", "subsequently", "it can be observed"
- Use natural connectors: "so", "which means", "because of this", "that's why", "we found that"
- Use "we" and "our" naturally — this is a team project report
- Mix sentence lengths — some short, some longer
- Occasionally start a sentence with "And" or "So" — students do this
- Keep it grounded and direct — no over-explaining
- Do NOT use bullet points
- Do NOT add any intro like "Here is the rewritten text" — just write it directly""",

    "storytelling": """Rewrite the text below so it sounds like a real person telling a story about what they built or did.

Rules:
- Write like a human, not a robot. Avoid phrases like "it is worth noting", "furthermore", "subsequently", "it can be observed"
- Use natural connectors like "so", "which means", "and then", "because of this", "that's why"
- Mix sentence lengths — some short. Some a bit longer and more detailed.
- Use "we" and "our" naturally
- Occasionally start a sentence with "And" or "So" — real people do this
- Don't over-explain. Keep it grounded and direct.
- Do NOT use bullet points
- Do NOT add any intro like "Here is the rewritten text" — just write it directly""",

    "formal_report": """Rewrite the text below for a formal report, but make it sound like it was written by a thoughtful human — not generated by AI.

Rules:
- Use formal language but avoid robotic AI phrases like "it is imperative", "it is worth noting", "subsequently", "furthermore"
- Vary sentence length — not everything should be long and complex
- Use occasional contractions sparingly where natural
- Connect ideas naturally, not with forced transitions
- Sound like a senior professional wrote this, not a language model
- Do NOT use bullet points
- Do NOT add any intro — just write the rewritten text directly""",

    "casual": """Rewrite the text below so it sounds like a real person casually explaining something to a friend or colleague.

Rules:
- Keep it relaxed and natural — like you're actually talking
- Use "we", "our", "basically", "so", "the thing is", "which is why"
- Short sentences are fine. Mix them in.
- Don't use stiff academic phrases at all
- Sound genuinely human — imperfect rhythm is good
- Do NOT use bullet points
- Do NOT add any intro — just write it directly""",

    "formal_professional": """Rewrite the text below for a professional business context. It must sound like it was written by a real human professional, not AI.

Rules:
- Be clear and direct — avoid vague filler phrases
- Do NOT use: "it is worth noting", "furthermore", "subsequently", "it is imperative", "in conclusion"
- Use concrete language — say exactly what happened or what something does
- Vary sentence lengths — short sentences add punch
- Sound confident and grounded, like a real person wrote this report
- Do NOT use bullet points
- Do NOT add any intro — just write the rewritten text directly""",

    "academic": """Rewrite the text below for an academic context, but make it sound like a real student or researcher wrote it — not AI.

Rules:
- Use academic vocabulary but avoid overused AI phrases like "it is worth noting", "it can be observed", "furthermore", "subsequently"
- Write in a way that sounds like a real person reasoning through ideas
- Vary sentence length — not every sentence needs to be long
- Use hedging naturally: "this suggests", "it seems", "one reason may be"
- Occasionally use simpler phrasing to break up density
- Do NOT use bullet points
- Do NOT add any intro — just write the rewritten text directly""",

    "conversational": """Rewrite the text below so it sounds like a real person writing a blog post or newsletter — warm, direct, and genuinely human.

Rules:
- Write like you're talking to someone, not presenting to them
- Use contractions naturally: "it's", "we've", "you'll", "that's"
- Short sentences are your friend. Use them.
- Avoid all AI-sounding phrases — no "furthermore", "it is worth noting", "subsequently"
- Sound like a person who actually cares about what they're writing
- Do NOT use bullet points
- Do NOT add any intro — just write it directly""",

    "technical": """Rewrite the text below for technical documentation. Make it sound like it was written by a real engineer, not generated by AI.

Rules:
- Be precise and direct — say exactly what something does
- Avoid vague filler: "it is important to note", "it can be observed", "in order to"
- Use active voice: "the component fetches..." not "the fetching of data is performed by..."
- Keep sentences short and scannable
- Sound like a developer wrote this for other developers
- Do NOT use bullet points
- Do NOT add any intro — just write it directly""",

    "creative": """Rewrite the text below in a creative, expressive way that sounds like a real human writer — not AI.

Rules:
- Use vivid language but don't be over-the-top
- Vary your sentence rhythm — short punchy sentences, then longer flowing ones
- Avoid AI clichés: "delve", "it is worth noting", "furthermore", "tapestry", "nuanced"
- Write with personality and voice
- Let imperfect rhythm stay — it sounds more real
- Do NOT use bullet points
- Do NOT add any intro — just write it directly""",
}

AGGRESSIVENESS_INSTRUCTIONS = {
    1: "Make light changes — fix flow and awkward phrasing but stay very close to the original wording.",
    2: "Moderately rewrite — restructure sentences, improve naturalness, add human-sounding connectors.",
    3: "Heavily rewrite — significantly rephrase, vary structure, make it sound like a real person wrote it from scratch while keeping the meaning."
}


async def rewrite_chunk(text: str, tone: str, aggressiveness: int, client: httpx.AsyncClient) -> str:
    tone_prompt = TONE_PROMPTS.get(tone, TONE_PROMPTS["btech_student"])  # FIX #1 — correct default
    aggr_instruction = AGGRESSIVENESS_INSTRUCTIONS.get(aggressiveness, AGGRESSIVENESS_INSTRUCTIONS[2])

    prompt = f"""{tone_prompt}

Aggressiveness: {aggr_instruction}

Text:
{text}

Rewritten:"""

    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": True,
        "options": {
            "temperature": 0.85,
            "top_p": 0.92,
            "repeat_penalty": 1.15,
            "num_predict": 1024
        }
    }

    # FIX #8 — Added try/except so LLM failure returns original text instead of crashing
    try:
        result_text = ""
        async with client.stream("POST", OLLAMA_URL, json=payload) as response:
            response.raise_for_status()
            async for line in response.aiter_lines():
                if line.strip():
                    chunk = json.loads(line)
                    result_text += chunk.get("response", "")
                    if chunk.get("done", False):
                        break
        return result_text.strip() if result_text.strip() else text

    except Exception as e:
        logger.warning(f"LLM rewrite failed for chunk, returning original. Error: {e}")
        return text  # graceful fallback


async def style_rewrite(merged_units: list[str], tone: str, aggressiveness: int) -> list[str]:
    batch_size = 3
    rewritten = []

    async with httpx.AsyncClient(timeout=None) as client:
        for i in range(0, len(merged_units), batch_size):
            batch = merged_units[i:i + batch_size]
            combined = "\n".join(batch)
            result = await rewrite_chunk(combined, tone, aggressiveness, client)
            rewritten.append(result)

    return rewritten
